---
steps:
- key: unit
  label: ":circleci: unit"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec
  - 'echo ''--- :circleci: run'''
  - bundle exec rubocop
  env: 
  plugins:
  - docker#v3.3.0:
      image: circleci/ruby:2.5.1-node
      workdir: "/buildkite-checkout"
- key: kafka-0.11
  label: ":circleci: kafka-0.11"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-0.11-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_11_0_11_0_3
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_11_0_11_0_3:
            image: wurstmeister/kafka:2.11-0.11.0.3
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-0.11-docker-compose.yml"
      run: primary
- key: kafka-1.0.0
  label: ":circleci: kafka-1.0.0"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-1.0.0-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_11_1_0_2
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_11_1_0_2:
            image: wurstmeister/kafka:2.11-1.0.2
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-1.0.0-docker-compose.yml"
      run: primary
- key: kafka-1.1
  label: ":circleci: kafka-1.1"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-1.1-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_11_1_1_1
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_11_1_1_1:
            image: wurstmeister/kafka:2.11-1.1.1
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-1.1-docker-compose.yml"
      run: primary
- key: kafka-2.0
  label: ":circleci: kafka-2.0"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-2.0-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_11_2_0_1
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_11_2_0_1:
            image: wurstmeister/kafka:2.11-2.0.1
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-2.0-docker-compose.yml"
      run: primary
- key: kafka-2.1
  label: ":circleci: kafka-2.1"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-2.1-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_12_2_1_1
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_12_2_1_1:
            image: wurstmeister/kafka:2.12-2.1.1
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-2.1-docker-compose.yml"
      run: primary
- key: kafka-2.2
  label: ":circleci: kafka-2.2"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-2.2-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_12_2_2_1
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_12_2_2_1:
            image: wurstmeister/kafka:2.12-2.2.1
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-2.2-docker-compose.yml"
      run: primary
- key: kafka-2.3
  label: ":circleci: kafka-2.3"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-2.3-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_12_2_3_1
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_12_2_3_1:
            image: wurstmeister/kafka:2.12-2.3.1
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-2.3-docker-compose.yml"
      run: primary
- key: kafka-2.4
  label: ":circleci: kafka-2.4"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-2.4-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_12_2_4_0
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_12_2_4_0:
            image: wurstmeister/kafka:2.12-2.4.0
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-2.4-docker-compose.yml"
      run: primary
- key: kafka-2.5
  label: ":circleci: kafka-2.5"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-2.5-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_12_2_5_0
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_12_2_5_0:
            image: wurstmeister/kafka:2.12-2.5.0
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-2.5-docker-compose.yml"
      run: primary
- key: kafka-2.6
  label: ":circleci: kafka-2.6"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-2.6-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_13_2_6_0
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_13_2_6_0:
            image: wurstmeister/kafka:2.13-2.6.0
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-2.6-docker-compose.yml"
      run: primary
- key: kafka-2.7
  label: ":circleci: kafka-2.7"
  commands:
  - 'echo ''~~~ :circleci: checkout'''
  - sudo cp -R /buildkite-checkout /home/circleci/checkout
  - sudo chown -R circleci:circleci /home/circleci/checkout
  - cd /home/circleci/checkout
  - 'echo ''--- :circleci: run'''
  - sudo apt-get update && sudo apt-get install -y cmake
  - 'echo ''--- :circleci: run'''
  - bundle install --path vendor/bundle
  - 'echo ''--- :circleci: run'''
  - bundle exec rspec --profile --tag functional spec/functional
  env: 
  plugins:
  - keithpitt/write-file#v0.2:
      path: ".buildkite/1634663090-kafka-2.7-docker-compose.yml"
      contents: |
        ---
        version: '3.6'
        services:
          network:
            image: ubuntu
            command: sleep infinity
          primary:
            image: circleci/ruby:2.5.1-node
            network_mode: service:network
            environment:
              LOG_LEVEL: DEBUG
            volumes:
            - "../:/buildkite-checkout"
            depends_on:
            - network
            - wurstmeister_zookeeper
            - wurstmeister_kafka_2_13_2_7_0
          wurstmeister_zookeeper:
            image: wurstmeister/zookeeper
            network_mode: service:network
          wurstmeister_kafka_2_13_2_7_0:
            image: wurstmeister/kafka:2.13-2.7.0
            network_mode: service:network
            environment:
              KAFKA_ADVERTISED_HOST_NAME: localhost
              KAFKA_ADVERTISED_PORT: 9094
              KAFKA_PORT: 9094
              KAFKA_ZOOKEEPER_CONNECT: localhost:2181
              KAFKA_DELETE_TOPIC_ENABLE: true
  - docker-compose#v3.1.0:
      config: ".buildkite/1634663090-kafka-2.7-docker-compose.yml"
      run: primary
